### ISSUE TITLE
Failed to load data from redy box

### ISSUE THREAD

**Issue by ruifigueiredo** [abmantis/homeassistant-custom-components#2]
2018-08-22 22:55:22 ERROR (MainThread) [custom_components.sensor.edp_redy_local] Failed to load data from redy box: Expecting value: line 1 column 1 (char 0)

**Comment by abmantis** [comment]
Are you on the Beta program? Check http://192.168.X.X:1234/api/devices to see if your redy box has the required endpoint.

**Comment by ruifigueiredo** [comment]
I'm not beta program. i have the widget at http://homeassistanturl:8123/state with devices but the devices is in the wrong state. in the logs I get the msg "2018-08-22 22:55:22 ERROR (MainThread) [custom_components.sensor.edp_redy_local] Failed to load data from redy box: Expecting value: line 1 column 1 (char 0"

**Comment by abmantis** [comment]
If you know the IP address of the re:dy box, check http://redy_box_ip_address:1234/api/devices

**Comment by ruifigueiredo** [comment]
CMD NOR FOUND ------------- VALID CMDS: varRITA varDevices varActions varSecurity varHeating varSound varDebug varMonitor xml sql

**Comment by abmantis** [comment]
I think the component only works for Beta testers.

**Comment by ruifigueiredo** [comment]
It's not an issue the box is with technical maintenance between the 23h and the 8h
thanks!

**Comment by abmantis** [comment]
@ruifigueiredo by the way, you could try using the new edp_redy component. Just copy `edp_redy.py`, `sensor/edp_redy.py`, `switch/edp_redy.py`, instead of `sensor/edp_redy_local.py`.
It supports controlling plugs and switches, and also provides power consumption as the old edp_redy_local.py
