### ISSUE TITLE
Other Whirlpool appliances

### ISSUE THREAD

**Issue by Shamshala** [abmantis/homeassistant-custom-components#6]
Hi,

i'm glad somebody managed to get Whirlpool's devices to work (but anything is better than their app :laughing: ). Is there any way to help you to get more appliances?
I have a microwave and i would like to get some basic info to HA. Unfortunately i'm not a programer to contribute on your project but i think i'm able to do everything in order to get needed info (based on your guidance).

Thank you!

**Comment by abmantis** [comment]
Hey @Shamshala. Thanks for your availability, but it would require too much effort to add a new appliance without being able to test it out directly.

**Comment by JesseWebDotCom** [comment]
I have a WIFI Whirlpool microwave and some coding experience.  Let me know how I can get started to help.
