### ISSUE TITLE
Error validating config file

### ISSUE THREAD

**Issue by tarrinho** [abmantis/homeassistant-custom-components#8]
Thanks for doing this. 

I’m trying to test it, but after copying those files to my custom_components/whirlpool/ and adding the text to the configuration file, I did a configuration test, but it doesn’t finish… it keeps loading and loading… which means that something is wrong. 

So I removed the whirlpool configuration, and I had success on the validation of the config file. 

What I’m I doing wrong?

**Comment by abmantis** [comment]
Have you tried rebooting HA?
Also, please check the logs, and ensure that the directory structure is correct: the folder `whirlpool` should be directly inside `custom_components`, and it should contain the .py files on it.

**Comment by tarrinho** [comment]
I found that because the password that I used started with a '@' it somehow corrupted the file inside: "__pycache__", so I deleted it and now I can do a config check - seams OK. (with the whirlpool config)
![imagem](https://user-images.githubusercontent.com/1039120/108981323-88558a00-7684-11eb-8f6f-c0243a87a299.png)

However, when I do a reboot to the HA to load the new configuration it gives me the following error:
![imagem](https://user-images.githubusercontent.com/1039120/108981035-3a408680-7684-11eb-9425-621c53163c4b.png)
and the log from the error states:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/whirlpool/__init__.py", line 31, in async_setup
    await auth.load_auth_file()
  File "/usr/local/lib/python3.8/site-packages/whirlpool/auth.py", line 95, in load_auth_file
    await self.do_auth()
  File "/usr/local/lib/python3.8/site-packages/whirlpool/auth.py", line 77, in do_auth
    "access_token": fetched_auth_data.get("access_token", ""),
AttributeError: 'NoneType' object has no attribute 'get'`

Please advise

**Comment by abmantis** [comment]
can you post the full log?

**Comment by tarrinho** [comment]
in the home-assistant.log the only information is limited to what I shared above, but you can see it here: 
https://securebin.pt4.tech/?b28c236942104e31#5KSbupXNuQMTHzBF2Yi9TKN4YDCfJfzoruX3So7p1Ghv

**Comment by abmantis** [comment]
Can you enable debug logs and try again? That should provide more info.
```
logger:
  default: warn
  logs:
    custom_components.whirlpool: debug
```

**Comment by tarrinho** [comment]
Thanks, I didn't knew how to enable them.

Done and please find here the complete log file:
https://securebin.pt4.tech/?9ee161e01785852d#C63ueDeA7SV6CFuL3vQph6c1woAmJBfXTxWS7U4ThZiJ

Please note, that from my understanding, I can't see anything else.

Btw, I've changed the password (@whirlpool site and HA) several times with the same result :/

**Comment by abmantis** [comment]
Have you added the logger snippet to the configuration.yaml? Can you share a screenshot? I think it is not being applied.

**Comment by tarrinho** [comment]
I did changed it as it shows here:
![image](https://user-images.githubusercontent.com/1039120/109277539-61778f00-780f-11eb-823c-47765907a309.png)
However, I found it strange as well, that was why I said above that I couldn't find anything. So I commented your lines and added mine to see if the configuration was really being picked up, and I got a really big log file, as a confirmation.

Nevertheless, the error states that during the get the token phase is having problems:
""access_token": fetched_auth_data.get("access_token", ""),"

Do you have a small script in python just to test the authentication?

**Comment by abmantis** [comment]
@tarrinho you can try the 'whirlpool_ac.py' from the lib repo: https://github.com/abmantis/whirlpool-sixth-sense

**Comment by tarrinho** [comment]
I did changed it as it shows here:
![image](https://user-images.githubusercontent.com/1039120/109277539-61778f00-780f-11eb-823c-47765907a309.png)
However, I found it strange as well, that was why I said above that I couldn't find anything. So I commented your lines and added mine to see if the configuration was really being picked up, and I got a really big log file, as a confirmation.

Nevertheless, the error states that during the get the token phase is having problems:
""access_token": fetched_auth_data.get("access_token", ""),"

Do you have a small script in python just to test the authentication?

**Comment by tarrinho** [comment]
Just saw your comment and tested it and my credentials work... really strange!!

```
$ python ./whirlpool_ac.py -e <email here> -p <password was entered here>
2021-02-26 22:45:02,802 [whirlpool.auth DEBUG]: Access token expired. Renewing.
2021-02-26 22:45:02,803 [whirlpool.auth DEBUG]: Fetching auth with user/pass
2021-02-26 22:45:03,776 [whirlpool.auth DEBUG]: Auth status: 200


------------------------------ MENU ------------------------------
1. Turn on
0. Turn off
+. Temp up
-. Temp down
C. Mode: Cool
H. Mode: Heat
F. Mode: Fan
S. Mode: Sixth Sense
2. Swing toggle
3. Turbo toggle
4. Eco toggle
5. Quiet toggle
6. Display toggle
u. Update status from server
p. Print status
v. Print raw status
r. Restart wifi
c. Custom command
q. Exit
-------------------------------------------------------------------
Enter your choice: 2021-02-26 22:45:04,513 [whirlpool.eventsocket DEBUG]: > CONNECT
version:1.1,1.0
wcloudtoken: <deleted token>
2021-02-26 22:45:04,594 [whirlpool.eventsocket DEBUG]: < CONNECTED
```

So if the credentials work, what I'm I doing wrong?

**Comment by abmantis** [comment]
On the configuration.yaml, are you putting your quoting your credentials?
Also, try to fully delete the whirlpool directory in the custom_integrations dir and copying it again.

**Comment by tarrinho** [comment]
Yes, and to double-check that, I've added to the __init__.py the following line:
"_LOGGER.debug("o username: %s e a password: %s", username, password)"

And confirmed in the log that the username/password that I've entered in the config file are the same.

I've also removed and copied the files again. I'm going to do some "debugging" with my limited knowledge, if you can remember something else for me to try, I would appreciate it.

**Comment by tarrinho** [comment]
I removed the assyncronos (await) 
![image](https://user-images.githubusercontent.com/1039120/109397053-a80edb80-792c-11eb-8501-85539a851789.png)

and got the following behaviour:
 - I was able to see all steps in the logs;
 - I was able to find the integrations menu the Whirlpool option;
![image](https://user-images.githubusercontent.com/1039120/109397125-076ceb80-792d-11eb-9ab7-ca6521cfaa4a.png)

However, when clicked to add it I got the following error:
"2021-02-27 18:44:51 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration whirlpool: No module named 'custom_components.whirlpool.config_flow'"

No sure if I'm going the wrong path :/

**Comment by abmantis** [comment]
You can't remove the await there, or it will not load auth correctly. Also, you should not try to set it up trough the UI.
Can you try the following?
- remove and re-add the files to make sure no changes are present
- set it up as instructed, using the configuration.yaml and not UI
- enable debug logs for everything in HA:
    ```
    logger:
      default: debug
    ```

The component lib should then print what is happening during auth. You can then grep by "whirlpool" and show me the logs (or just send everything).

**Comment by tarrinho** [comment]
here it is: https://securebin.pt4.tech/?28698427d95f2caa#EDf6ZwWXGeYmbvk7Pjoq4rMp3AZ6Yv98YkfSki78TbyN

I found this strange:
"2021-02-27 19:11:54 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [139956153078496] Sending {'id': 43, 'type': 'result', 'success': True, 'result': [{'notification_id': 'invalid_config', 'message': 'The following integrations and platforms could not be set up:\n\n - whirlpool\n\nPlease check your config and logs(/config/logs).', 'status': 'unread', 'title': 'Invalid config', 'created_at': datetime.datetime(2021, 2, 27, 19, 11, 52, 787882, tzinfo=datetime.timezone.utc)}]}"
2021-02-27 19:12:50 DEBUG (SyncWorker_4) [homeassistant.util.json] JSON file not found: /config/custom_components/whirlpool/translations/en.json
2021-02-27 19:12:50 DEBUG (SyncWorker_3) [homeassistant.util.json] JSON file not found: /config/custom_components/whirlpool/translations/en-GB.json

Note: I would send my complete log file, but it has 7,5 Mb - several noisy integrations

**Comment by abmantis** [comment]
The logs don't show what is happening after the component doing auth, so I need to see more. You can probably filter and show only lines that have whirlpool on it.

**Comment by tarrinho** [comment]
That was what I did (grep whirlpool homeassistant.log).

Nevertheless, this time I went with a different approach. Removed everything that was sensitive (I hope 🙏 )

https://securebin.pt4.tech/?9affc6fcffd6831f#4AmvE2f9GBdMjeEtRam5aHBs4CnrxxvrLLPx2ouUYM1n

**Comment by abmantis** [comment]
It seems that the component is unable to reach the server:
```2021-02-28 18:36:36 DEBUG (MainThread) [whirlpool.auth] Auth status: 404```

I just tested it here, and it is working fine. Do you have any firewall or DNS server (pihole?) that could be preventing your HA instance from reaching the servers?

**Comment by tarrinho** [comment]
No, I don't have anything like that. 

Can you tell me what is the URL that it is trying to reach?

**Comment by abmantis** [comment]
See https://github.com/abmantis/whirlpool-sixth-sense/blob/b70705af81f1a9407abf4511737ef2b3c13ee751/whirlpool/auth.py#L24

**Comment by tarrinho** [comment]
I've tested with curl from the HA server and I can reach the server (POST):
![image](https://user-images.githubusercontent.com/1039120/109474622-9c2a3300-7a6c-11eb-9ac5-a94288b2f4c7.png)

However, that code isn't in the module for the HA, right? That is only for your standalone application that also works from my side. 

In the HA module you are using the "from whirlpool.auth import Auth", where can I get the code from this in my server? (my idea is to validate, both the version, and to check what is this doing)

Thanks

**Comment by abmantis** [comment]
Yes, it is the same code. The version that is published in pypi is the one that is on github. Also, that url has never changed.
You can try using the standalop app to print the full payload sent to that server, and try it with curl to see if it really works (it should give a 202 IIRC and not 400).

**Comment by tarrinho** [comment]
Ok, so I just ran your standalone app -> "python whirlpool_ac.py" and it gave me a 200 code, which means that the .whirlpool_auth.json has a valid token.
So after that, I ran my curl:
![image](https://user-images.githubusercontent.com/1039120/109508668-01dfe480-7a98-11eb-9805-618a26a05c8c.png)
"curl --trace-ascii /dev/stdout -i -H "Content-Type: application/x-www-form-urlencoded" -H "Brand: Whirlpool" -H "WP-CLIENT-REGION: EMEA" -H "WP-CLIENT-BRAND: WHIRLPOOL" -H "WP-CLIENT-COUNTRY: EN" -d @.whirlpool_auth.json https://api.whrcloud.eu/oauth/token"

but it gave me this error:
{"timestamp":1614607805153,"status":401,"error":"Unauthorized","message":"Full authentication is required to access this resource","path":"/oauth/token"}

What am I missing?

**Comment by abmantis** [comment]
The json file is not supposed to be used directly as the payload. You can log the auth_data variable to see the payload. 
If you need, you can reach me on the home assistant discord server.

**Comment by tarrinho** [comment]
Just to close this thread, the problem was with the username (missing one letter).

So many thanks to abmantis.

One last thing, for google to crawl this information (and also thanks to abmantis), if you need to access via curl just do:
`curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Brand: Whirlpool" -H "WP-CLIENT-REGION: EMEA" -H "WP-CLIENT-BRAND: WHIRLPOOL" -H "WP-CLIENT-COUNTRY: EN"  -d "client_id=whirlpool_android&client_secret=i-eQ8MD4jK4-9DUCbktfg-t_7gvU-SrRstPRGAYnfBPSrHHt5Mc0MFmYymU2E2qzif5cMaBYwFyFgSU6NTWjZg&grant_type=password&username=>email<&password=>password<" https://api.whrcloud.eu/oauth/token`
